[versions]
#plugins
kotlin = "2.3.0"
agp = "8.13.2"

#libraries
appcompat = "1.7.1"
material = "1.13.0"
coroutinesCore = "1.10.2"
junit = "4.13.2"
junitExt = "1.3.0"
espressoCore = "3.7.0"
coreKtx = "1.17.0"
activityKtx = "1.12.2"
constraintLayout = "2.2.1"
androidUtilities = "4.12.1"
androidBinding = "1.12.2"    # for sample only
androidDialog = "6.3.5"     # for sample only
androidPlayer = "4.3.2"     # for sample only
documentfile = "1.1.0"     # for sample only

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesCore" }
junit = { module = "junit:junit", version.ref = "junit" }
junitExt = { module = "androidx.test.ext:junit", version.ref = "junitExt" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
activityKtx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
android-utilities = { module = "com.github.toyota-m2k:android-utilities", version.ref = "androidUtilities" }
#android-logger = { module = "com.github.toyota-m2k:android-logger", version.ref = "androidLogger" }
android-binding = { module = "com.github.toyota-m2k:android-binding", version.ref = "androidBinding" }
android-dialog = { module = "com.github.toyota-m2k:android-dialog", version.ref = "androidDialog" }
android-player = { module = "com.github.toyota-m2k:android-media-player", version.ref = "androidPlayer" }
documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }

[plugins]
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
